<a href="https://colab.research.google.com/github/Haizhepi/MLCheatSheet/blob/master/NumpyCheatSheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.3.0'

In [35]:
mylist = [1, 2, 3]
np.array(mylist)

array([1, 2, 3])

In [36]:
nested_list = [[1, 2], [3, 4], [5, 6]]
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
# [start, end) optional: step size
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [38]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [42]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.random.rand(2)

array([0.09178413, 0.34518624])

In [44]:
np.random.rand(3, 4)

array([[0.66275252, 0.44171349, 0.55148779, 0.70371249],
       [0.58940123, 0.04993276, 0.56179184, 0.76635847],
       [0.91090833, 0.09290995, 0.90252139, 0.46096041]])

In [45]:
# normal dis
np.random.randn(5, 5)

array([[ 5.05645125e-01, -8.15271110e-01,  3.89150951e-01,
        -4.24962470e-01,  3.96231519e-02],
       [-5.27963922e-01, -5.10303679e-01, -8.88285149e-01,
         1.08762473e+00,  6.73392264e-01],
       [-1.06731704e+00,  1.21804998e+00,  3.36371255e+00,
        -8.32253403e-01, -3.40348381e-01],
       [-1.85857154e+00,  8.23065599e-04,  3.51574483e-01,
         1.52150885e+00, -6.80474137e-01],
       [ 9.38057708e-01, -6.81414713e-01, -2.01098083e-01,
        -1.74886440e-02, -1.78791213e+00]])

In [46]:
np.random.randint(1, 100, (2, 2))

array([[60,  8],
       [79, 71]])

In [47]:
np.random.seed(32)
np.random.rand(4)

array([0.85888927, 0.37271115, 0.55512878, 0.95565655])

In [48]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
ranarr

array([ 7, 25,  3, 37, 42,  9,  4, 11, 17,  3])

In [49]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
ranarr.max()

42

In [51]:
ranarr.argmax()

4

In [52]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[1:5]

array([1, 2, 3, 4])

In [54]:
arr[:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr = np.arange(0, 11)
slice_of_arr = arr[0:5]
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [59]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[-1]

array([35, 40, 45])

In [61]:
arr_2d[0, 2]

15

In [62]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [63]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [65]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [69]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [72]:
# only warning, not exception
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
1 / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [74]:
arr.sum()

45

In [75]:
arr.var()

8.25

In [76]:
arr.std()

2.8722813232690143

In [78]:
arr_2d = np.arange(0, 25).reshape(5, 5)
arr_2d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr_2d.sum()

300

In [81]:
arr_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [82]:
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])