<a href="https://colab.research.google.com/github/Haizhepi/MLCheatSheet/blob/master/TF1_syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
print(tf.__version__)

2.3.0


In [4]:
hello = tf.constant("Hello")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
with tf.Session() as sess:
  res = sess.run(hello + world)

In [8]:
print(res)

b'HelloWorld'


In [9]:
a = tf.constant(10)
b = tf.constant(20)

In [10]:
type(a)

tensorflow.python.framework.ops.Tensor

In [11]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [12]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
  result = sess.run(a + b)

In [14]:
result

30

In [15]:
const = tf.constant(10)

In [16]:
fill_mat = tf.fill((4, 4), 10)

In [17]:
myzeros = tf.zeros((4, 4))

In [18]:
myones = tf.ones((4, 4))

In [19]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [20]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [21]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [22]:
sess = tf.InteractiveSession()

In [23]:
for op in my_ops:
  print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-0.815438   -1.1627268   0.11584654  0.1170062 ]
 [ 0.7766001   0.5235548  -0.28051755  0.37848285]
 [-1.0617232   0.18090308 -0.52771306 -0.23477693]
 [ 0.7842454   1.4322177  -0.87291193  0.1166519 ]]
[[0.7121295  0.16991186 0.49617612 0.5642718 ]
 [0.8245194  0.3466345  0.9592217  0.38939166]
 [0.83572793 0.9630513  0.11330712 0.9256017 ]
 [0.28695154 0.99579966 0.16573167 0.51427996]]


In [25]:
a = tf.constant([ [1, 2], [3, 4] ])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [27]:
b = tf.constant([[10], [100]])

In [29]:
result = tf.matmul(a, b)

In [30]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

## **TF Graphs**

In [31]:
n1 = tf.constant(1)
n2 = tf.constant(2)

In [32]:
n3 = n1 + n2

In [33]:
with tf.Session() as sess:
  result = sess.run(n3)

In [34]:
print(result)

3


In [35]:
print(tf.get_default_graph())

In [36]:
g = tf.Graph()

In [37]:
print(g)

In [38]:
graph_one = tf.get_default_graph()

In [39]:
graph_one

In [40]:
graph_two = tf.Graph()

In [41]:
graph_two

In [42]:
with graph_two.as_default():
  print(graph_two is tf.get_default_graph())

True


In [43]:
print(graph_two is tf.get_default_graph())

False


## **Var & Placeholders**

In [44]:
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [46]:
my_tensor = tf.random_uniform((4, 4), 0, 1)

In [47]:
my_tensor

<tf.Tensor 'random_uniform_2/RandomUniform:0' shape=(4, 4) dtype=float32>

In [48]:
my_var = tf.Variable(initial_value=my_tensor)

In [49]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [ ]:
# sess.run(my_var)

In [51]:
init = tf.global_variables_initializer()

In [52]:
sess.run(init)

In [53]:
sess.run(my_var)

array([[0.45872784, 0.66316783, 0.75225365, 0.8264054 ],
       [0.7720554 , 0.633765  , 0.06855547, 0.10530591],
       [0.66179574, 0.6743854 , 0.10654712, 0.01934648],
       [0.01920533, 0.19167042, 0.58581495, 0.50748825]], dtype=float32)

In [54]:
ph = tf.placeholder(tf.float32)